Supress QML warning
Summary:
Role LegacyWinIdList can be null, for example on a StartupItem or on
Wayland. This means we access a property on an undefined object.

Fixes:
share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipDelegate.qml:41:
TypeError: Cannot read property 'length' of undefined

Reviewers: #plasma

Subscribers: plasma-devel

Tags: #plasma

Differential Revision: https://phabricator.kde.org/D2495